---

# define the initial environment conditions
environment_width: 50
environment_height: 50
num_starting_trees: 100
max_food_on_tree: 100
starting_population_size: 50

# set probability of new trees spawning
tree_spawn_prob: 0.01

# set probability of ant following a trail vs searching for new food sources
follow_prob: 1

# set the initial strength of a food trail
trail_depreciation_time: 20

# set the depreciation rates of the ants
max_lifespan: 13000
max_without_food: 300

# set how long an ant will go till he is hungry
time_till_hungry: 72

# set how many ants the queen lays per day
num_ants_laid_daily: 1
time_till_maturity: 1700 #2000

